### PR TITLE
Example: Switching to TypeScript

### PR DESCRIPTION
**Pull request by pparke**
Hey! Love the repo and saw that some people mentioned TS so I wanted to provide a working example in case you decide to switch. The demo, tests and the build process are working and it's emitting both CJS and ESM modules in case you want to publish it to NPM. Right now it's allowing a lot of `any` types in the build since it would be a lot of work to specify all of those but I did add a few types here and there to get things working. If you run `npm run check` you'll see there are a lot of types to add but mixed in there will be some things that are potentially bugs.

I see that my branch is behind now so don't worry about merging this but feel free to use it as an example!

### CODE REVIEW

**Comment by eduardoleao052** [comment]
This is awesome. I'm looking through your code, and although I have made some alterations (so it is currently conflicting), I'll still definitely implement your suggestions on the current branch. Thank you so much for the help!

**Comment by medic-code** [comment]
@eduardoleao052  Saw the article on hackernews and great job I'm a fan! Some good config suggestions in the commit!

I'm not a TS expert but it might be worth opening another PR specifically (or couple) for TS support and incrementally add type annotations as you go, you've got a good starting config setup that could be merged in this PR so might want to merge that with main. 

Just my two cents and by no means should be followed, would be starting with method arguments and returns for those that should be annotated rather than inferred might be a good first step.

**Comment by pparke** [comment]
@eduardoleao052 I've applied the same changes to bring my branch up to date. I wouldn't mind changing the base branch that the PR is against if you want to keep `main` in JS, just let me know if you want to do that and what the branch name is. I think you could find quite a few potential bugs by running `npm run check` in this branch.

I also switched over to using `tsx` instead of `ts-node` and `pkgroll` for building to make the configuration simpler.

**Comment by eduardoleao052** [comment]
> @eduardoleao052 I've applied the same changes to bring my branch up to date. I wouldn't mind changing the base branch that the PR is against if you want to keep `main` in JS, just let me know if you want to do that and what the branch name is. I think you could find quite a few potential bugs by running `npm run check` in this branch.
> 
> I also switched over to using `tsx` instead of `ts-node` and `pkgroll` for building to make the configuration simpler.

That’s great! I was about to try to it, great timing! I’ll review it during the weekend, and merge it in! Thank you so much @pparke and @medic-code!

**Comment by pparke** [comment]
No problem! Glad you like the changes! I did a rebase but you might still want to check the commits that re-applied the changes since I had to resolve those manually. They weren't too complex so I think I got everything but a quick review never hurts. I named the commits according to the ones they were re-implementing so it should be easy to do a side by side comparison.

The one thing I haven't done is to figure out how to include the JS for the demo. I think copying the file from dist to the demo dir during the build would be best.

**Comment by pparke** [comment]
Just made that change so that the demo will work without building first.

**Comment by eduardoleao052** [comment]
> Just made that change so that the demo will work without building first.

Cool!

**Comment by eduardoleao052** [comment]
Ok, it's all working! Now I'll get into solving the 263 type errors! :D
The code is really nice, and pretty minimalistic! I just have a couple of questions (as I'm a bit of a TypeScript noob):
- 1 - __About the dev dependencies:__ `typescript`, `pkgroll`, `tsx` and `copyfiles` are being used in `package.json`. But are `del-cli`, `move-file-cli`, and `semantic-release` being used at all?
- 2 - __About TS:__ what is `tsconfig.strict.json`? Why is `tsconfig.json` not sufficient?
- 3 - __And a more begginer-like question:__ when we run the scripts in `package.json`, such as `test`, it runs fine (because I have insntalled the dependency `tsx`). However, if I run `tsx ./tests/test.ts` directly on the terminal, I get the error message: `tsx: command not found`. Do you know why that is?

With these remarks out of the way, thank you so much for the help! I'm currently editing your branch on VS, and after adding all types, I'll merge it into main.

**Comment by eduardoleao052** [comment]
Was just making sure, thanks! Didn't want to remove them and blow your code up lol

**Comment by pparke** [comment]
Glad to hear it's working! That is a lot of errors but they'll go by quickly and you'll probably find some bugs or missed cases while you're addressing them, it's a good way to get familiar with the TS syntax as well. I can help out with them as well.

- 1 - Good catch! I completely forgot to uninstall those when I removed them from the scripts. I just pushed a change to remove them.
- 2 - `tsconfig.strict.json` only differs from `tsconfig.json` in that I re-enabled the rules against `noUnusedLocals`, `noUnusedParameters` and `noImplicitAny`. You don't have to have a separate config file normally but I thought it might be helpful in case you wanted to change things in the main `tsconfig.json` which will be used by default by VSCode or any editor that supports type checking. The `check` script in `package.json` is using the strict config so that it will output errors like so `tsc -p ./tsconfig.strict.json --noEmit`, the `noEmit` flag tells it to not output transpiled JS files.  Alternatively you can pass those options to `tsc` like this `tsc --noUnusedLocals --noUnusedParameters --noImplicitAny`. Once all of the type check errors are resolved the strict config can be deleted and the rules can be re-enabled in the main one.
- 3 - When you run a `package.json` script with `npm run` it will use the packages that are installed in the `node_modules` folder. If you want to run a package on the command line without using a script you should either install the package globally with `npm i -g <package name>` see https://docs.npmjs.com/downloading-and-installing-packages-globally or use `npx` https://docs.npmjs.com/cli/v7/commands/npx I'd recommend using `npx` unless you want to have the package as a command line tool that you use a lot.

I'm glad I could contribute to the project! I've been trying to learn more about ML and how Transformers work but it's been difficult because I learn best by trying things out in code and I'm not the best with Python so when I saw this repo I was really excited to have something I could experiment with while using all of the JS knowledge I have. I'd be happy to help out with any JS or TS questions you have or if you get stuck while trying to define a complex type or interface. TS can be frustrating sometimes but it's worth it to catch bugs and have better autocomplete.

**Comment by medic-code** [comment]
Also happy to help with the TS, i'm trying to learn more about ML and Transformers myself, i do have python knowledge but spent most of my experience in web dev.

In terms of the other dev dependencies how should i best contribute ?  Its probable that this PR is going to be on going for a bit. Happy to add some commits to the branch in this PR.

**Comment by pparke** [comment]
@eduardoleao052 since @medic-code has kindly offered to help out as well it might be better for you to create a new branch in your repo called something like `develop` and then I can change the base of this PR to that branch instead of `main`. The benefit of doing that is that you could then merge this PR into `develop` and commit your changes as you work on resolving the type errors to that branch. That way @medic-code and I could make other PRs against the `develop` branch to also fix type errors or to add the tools that @medic-code was talking about. I didn't intend to make you fix all 200+ type errors yourself! 😄 

This is known as the [Gitflow Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) which is sometimes necessary for large features like converting to TS if you don't want to merge things into `main` until they are 100% complete. Normally you would want to use the [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) workflow and keep the features as small as possible. As you can see I'm also using the [Forking Workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow) which is usually best when contributing to someone else's repo.

**Comment by medic-code** [comment]
Yep agreed @pparke a dev branch would be useful and yep it would allow us to incrementally fix these errors together and add additional improvements without the constraint.

**Comment by eduardoleao052** [comment]
Hello! Thank you for your answers @pparke, I think its all clear now.

I started adding types today, and `npm run check` is already throwing no errors for `utils.ts`, `layers.ts` and `optim.ts`. 

I then pushed the PR into the `develop` branch (great idea, @medic-code!), so if you want to help with the other types (as well as chack that I have not messed something up) I would love it!

The only things I was not really familiar with were:
 - 1 - When adding types for arrays, is it a better convention to use `(number | string)[]` or `Array<number | string>`?
 - 2 - In `layers.js`, you created a `Interface` object. Does that mean that remove the necessity to annotate all methods manually? or just provides a blank slate on which you'll build your object normally (I ask because I've noticed that it's necessary to declare `[key: string]` and `mode` inside the object even though it was already typed in the Interface)?

All in all - it's all working really well, and the bug fixes are pretty quick to solve. Thanks for the help again @pparke @medic-code !

**Comment by medic-code** [comment]
1. To my knowledge there's no real objective difference, the latter is using generic syntax and i may prefer this if i'm using lots of generics or the array elements are complex (objects with specific properties I want to declare types for).

2. i think but could be wrong (@pparke will be able comment better than i) that its more about that the interface informs about the shape of the class but the class is responsible for implementation, so TS uses the class index signature to check that the class actually implements the methods and properties.

**Comment by pparke** [comment]
Ok, pushing your current changes including those in this PR to `develop` works though normally you would create a new branch off of `main` and then I would rebase this PR onto it but it'll work this way too. I'll try changing the base of this PR though I'm not sure what will happen if there are no differences, but there's one way to find out 😄 

- 1 - I normally write array types as `(number | string)[]` and I think that's considered the preferred form but it does mean the same thing as `Array<number | string>` so it's really up to you but it's best to choose one style and stick to it.
- 2 - You can certainly remove the type annotations from the methods if they are defined in the interface, the type checking, hover info, and autocomplete will still work. It's another one of those personal preference things, I like to keep the types in the method implementation so that I don't have to look at the interface or hover over the method name to see them but if you prefer having very terse and clean looking methods then you can leave them out.

Noticing the additional `[key: string]: Module | Parameter | Tensor | any;` annotation in the class is a good catch. I added it because I wasn't sure exactly which properties you were adding or if you intended to allow any property to be dynamically added later since you seemed to be extending the built in Object. If you want TS to be ok with it working like an Object and allowing any and all properties to be added then you'll need to keep that annotation in there. However, if you know which properties/members you'll be adding in all of the classes that derive from Module then you can define interfaces for those classes and add types for them.

**Comment by pparke** [comment]
A type for `mode` should be added to the interface as well to make sure it is clearly defined. If it should only accept certain values you can use the same [literal type](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types) union that I was with `"train" | "eval"` and you can add more string values to it as needed.

**Comment by eduardoleao052** [comment]
Cool, thanks for the answers @pparke, @medic-code! If you want, I can do what you said, I just pushed a different branch since I had already made some changes (type annotations) on top of your code locally, with `git fetch origin pull/fork/head:branch`.
If you want (and if you have not started working on `develop` yet)  I could do what you asked, and branch it off `main`. 
My only concern is making sure that you two are added as contributors as well if I merge the `develop` branch into main :D

**Comment by eduardoleao052** [comment]
@medic-code I notice you forked `develop` a while back, have you made any changes already? If not, I'll make a new `develop` branch off main to pass this PR onto.

**Comment by medic-code** [comment]
Not to `develop` branch yet, i've branched off from it to add some configs, nothing that wont take 5 minutes to re-do on new `develop` branch, so go for it.

**Comment by pparke** [comment]
Glad to help! I haven't started working on the `develop` branch yet so if @medic-code hasn't committed any changes either then it should be ok. I'm just thinking about the order we'd need to do things in, if you reset `develop` back to what's currently in `main` then I'll have to rebase my PR on it and you'll need to merge it and then you would need to rebase your local copy with your changes onto `develop` I think.

**Comment by pparke** [comment]
We should still appear as contributors when you merge changes from `develop` into `main` as long as you don't squash all the commits into one.

**Comment by eduardoleao052** [comment]
Done!

**Comment by pparke** [comment]
Thanks! I've changed the base of this PR to `develop`.

**Comment by eduardoleao052** [comment]
Ok, added my local changes to `develop`. Sorry about the small mess @medic-code, hope it didn't jeopardize your progress too much.

**Comment by pparke** [comment]
Awesome! Good work everyone!

**Comment by eduardoleao052** [comment]
Good work! Btw, since this PR is merged, if I want to ask something or plan a push, how would it be best for me to contact you?

**Comment by pparke** [comment]
@eduardoleao052 you can email me directly at pparke **at** foxrock **dot** dev if I'm not responding to @ mentions on GitHub but like @medic-code suggested making a new issue or PR and tagging me should normally work 😄

**Comment by eduardoleao052** [comment]
I created a new issue and linked it to the `develop` branch. However, I couldn't yet tag you two to it @pparke @medic-code

**Pull request merged**
