### PR TITLE
Add Prettier/ESLint/Jest configs

### PR DESCRIPTION
**Pull request by medic-code**
**Changes made**
1. Added prettier deps and config files to project 
2. Added ESLint deps and config files to project
3. Added necessary deps and config for ESlint and prettier to work synchronously
4. Added necessary config for TypeScript to communicate with ESlint 
5. Added jest deps and configuration 
6. Added minimal scripts for linting, formatting and testing
7. Automatic fixes to code brought up by ESLint and Prettier settings

 **Motivation and Context**
1. Adding Prettier and ESlint for a consistent developer experience, minimal settings for now but open to changes and preferences in future.
3. Added Jest as all-in-one test infrastructure - will help scale the project for unit and integration testing and provide useful helper functions built for testing software.

**Not in current scope of PR**
1. I have not added husky/lint-stage yet as will need to migrate to TS and fix eslint/ts errors before i can add this, as it will not allow the commits / pushes to repo until these are fixed.
2. I have not changed the current unit tests to jest compatible yet, as the focus for this PR is dev setup.

Once successful migration of TS will implement husky and lint-staged for automatic prettier script running and ensure no eslint errors on commits to project.

Additionally in a separate PR I will ensure the tests are jest compatible.

### CODE REVIEW

**Comment by eduardoleao052** [comment]
Hey, thanks for the commit! So from what I understood, eslint is not going to work until all files have correct TS syntax. Is that right? So running `npm run lint` now will cause errors. Also, I noticed that running `npm test` is running the tests, but throwing an error in the end: `Your test suite must contain at least one test.`

Finally, when pushed into main, is it necessary and/or common practice to leave all of these files in the root directory? I'm talking about: `.babelrc`, `.eslintignore`, `.eslintrc`, `prettierignore`, `.prettierrc` and `jest.config.cjs`.

**Comment by medic-code** [comment]
1. When you configure TS with ESlint, TS compilation errors will show up in your IDE without needing to run check, so yes `npm run lint` will show the TS relate errors.
2. Tests throws an error because jest will look at files with test in the file name in your project, but it only recognises tests that are in a `describe` or `it/test` method. It still runs the function in the test file as you can see from the console.logs, so the test still runs as it currently is. This will be fixed once we've used the jest syntax. 
3. Its common practice to have these files at the root.

**Comment by eduardoleao052** [comment]
Ok, understood! I'll try to correct all TS errors now. And then, as you said, you open another PR with the husky/lint-stage and correct jest syntax. Is that ok?

**Comment by medic-code** [comment]
Definitely don't feel pressure to fix them all yourself, think this is a task we can all contribute to! 

Husky/lint-staged are nice add ons, so definitely can wait till everything has been migrated to TS but yep will open another PR for that. Ill open the next PR with migrated jest unit tests as there's no blocker there :).

**Comment by eduardoleao052** [comment]
Ok! I'll now work on fixing all TS bugs on test.ts and tensor.ts.

**Pull request merged**
